export const FEATURE_KEYS = [
  "UNLIMITED_GALLERIES",
  "UNLIMITED_CLIENTS",
  "CLIENT_FAVORITES",
  "COMMENTS",
  "PASSWORD_PROTECTION",
  "CUSTOM_SLUGS",
  "SLIDESHOW_SHARING",
  "DOWNLOAD_ANALYTICS",
  "GOOGLE_IMPORT",
  "SMART_ALBUMS",
  "CUSTOM_DOMAINS",
  "WEBSITE_BUILDER",
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[number];

/** Human-readable labels for admin UI and error messages */
export const FEATURE_LABELS: Record<FeatureKey, string> = {
  UNLIMITED_GALLERIES: "Unlimited galleries",
  UNLIMITED_CLIENTS: "Unlimited clients",
  CLIENT_FAVORITES: "Client favorites & notes",
  COMMENTS: "Gallery comments",
  PASSWORD_PROTECTION: "Password-protected galleries",
  CUSTOM_SLUGS: "Custom gallery slugs",
  SLIDESHOW_SHARING: "Slideshow & social sharing",
  DOWNLOAD_ANALYTICS: "Download tracking & analytics",
  GOOGLE_IMPORT: "Google Drive & Google Photos import",
  SMART_ALBUMS: "Smart albums",
  CUSTOM_DOMAINS: "Custom domains",
  WEBSITE_BUILDER: "Website builder",
};

/** Default feature mapping per tier label — used as fallback when DB has no TierFeature rows */
export const DEFAULT_TIER_FEATURES: Record<string, FeatureKey[]> = {
  Free: [],
  Solo: [
    "UNLIMITED_GALLERIES",
    "UNLIMITED_CLIENTS",
    "CLIENT_FAVORITES",
    "COMMENTS",
    "PASSWORD_PROTECTION",
    "CUSTOM_SLUGS",
    "SLIDESHOW_SHARING",
  ],
  Studio: [
    "UNLIMITED_GALLERIES",
    "UNLIMITED_CLIENTS",
    "CLIENT_FAVORITES",
    "COMMENTS",
    "PASSWORD_PROTECTION",
    "CUSTOM_SLUGS",
    "SLIDESHOW_SHARING",
    "DOWNLOAD_ANALYTICS",
    "GOOGLE_IMPORT",
    "SMART_ALBUMS",
    "CUSTOM_DOMAINS",
  ],
  "Pro Studio": [
    "UNLIMITED_GALLERIES",
    "UNLIMITED_CLIENTS",
    "CLIENT_FAVORITES",
    "COMMENTS",
    "PASSWORD_PROTECTION",
    "CUSTOM_SLUGS",
    "SLIDESHOW_SHARING",
    "DOWNLOAD_ANALYTICS",
    "GOOGLE_IMPORT",
    "SMART_ALBUMS",
    "CUSTOM_DOMAINS",
    "WEBSITE_BUILDER",
  ],
  Unlimited: [
    "UNLIMITED_GALLERIES",
    "UNLIMITED_CLIENTS",
    "CLIENT_FAVORITES",
    "COMMENTS",
    "PASSWORD_PROTECTION",
    "CUSTOM_SLUGS",
    "SLIDESHOW_SHARING",
    "DOWNLOAD_ANALYTICS",
    "GOOGLE_IMPORT",
    "SMART_ALBUMS",
    "CUSTOM_DOMAINS",
    "WEBSITE_BUILDER",
  ],
};
